name: final_ibilling
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  dropdown_button2: ^2.3.9
  pinput: ^5.0.0

  #  localization
  easy_localization: ^3.0.7


  #  state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  equatable: ^2.0.7

  #  injection
  get_it: ^8.0.3

  #  Network
  dio: ^5.7.0

  #  Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.5
  local_auth: ^2.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/fonts/Ubuntu/



  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
          weight: 200
          style: italic

